# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
