# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0007_auto_20190905_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_event',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
