# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20190829_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idEvent',
            field=models.IntegerField(default=None),
        ),
    ]
