# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_task_idevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='idEvent',
            new_name='id_event',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
